#!/usr/bin/env python3
"""codemap.py KB_DIR [--depth N] > KB_DIR/codebase.md : the fact skeleton of the codebase knowledge file.

Everything printed is counted from the ut code index (KB_DIR/index/index.json, built with the compile DB) and, if
imported, its coverage (index/coverage.json). The sections marked `(agent)` are left for the agent to write from the
code and the docs, each line with its source (file:line or doc path); SKILL-MAKER.md step 9 says how.

Components are production directories (headers join the directory of the source file with the same name), collapsed
to --depth path parts (default: the smallest depth giving <= 30 components)."""
import collections, json, os, re, sys, time


def main(a):
    if not a or a[0].startswith('-'):
        print(__doc__); sys.exit(2)
    kb = a[0]
    depth = int(a[a.index('--depth') + 1]) if '--depth' in a else None
    ix = json.load(open(os.path.join(kb, 'index', 'index.json')))
    prof = json.load(open(os.path.join(kb, 'kb.json'))).get('profile', {}) if os.path.exists(os.path.join(kb, 'kb.json')) else {}
    cov = {}
    cp = os.path.join(kb, 'index', 'coverage.json')
    if os.path.exists(cp):
        cov = json.load(open(cp)).get('files', {})
    tpaths = [p.rstrip('/') for k in ('test_paths', 'mock_paths') for p in prof.get(k, [])] or ['tests', 'test']
    is_test_file = lambda f: any(f == t or f.startswith(t + '/') for t in tpaths)
    F = ix['functions']
    prod = {i: f for i, f in F.items() if f['kind'] != 'test' and not is_test_file(f['file'])}
    tests = {i: f for i, f in F.items() if f['kind'] == 'test'}

    # components: directories of production files, headers joined to their source's directory
    srcdir = {}
    for f in {f['file'] for f in prod.values()}:
        if not f.endswith(('.h', '.hpp', '.hh', '.hxx')):
            srcdir.setdefault(os.path.splitext(os.path.basename(f))[0], os.path.dirname(f))
    def comp_of(f, d):
        base = os.path.splitext(os.path.basename(f))[0]
        dirn = srcdir.get(base, os.path.dirname(f)) if f.endswith(('.h', '.hpp', '.hh', '.hxx')) else os.path.dirname(f)
        parts = dirn.split('/') if dirn else ['.']
        return '/'.join(parts[:d])
    files = {f['file'] for f in prod.values()}
    if depth is None:
        depth = 1
        while depth < 6 and len({comp_of(f, depth + 1) for f in files}) <= 30 and len({comp_of(f, depth + 1) for f in files}) > len({comp_of(f, depth) for f in files}):
            depth += 1
    comp = {i: comp_of(f['file'], depth) for i, f in prod.items()}

    callers, callees = collections.defaultdict(set), collections.defaultdict(set)
    for c in ix['calls']:
        callers[c['to']].add(c['from'])
        callees[c['from']].add(c['to'])

    def tests_reaching(i, hops=2):
        direct, allt, frontier, seen = set(), set(), {i}, {i}
        for h in range(hops + 1):
            nxt = set()
            for x in frontier:
                for c in callers.get(x, ()):
                    if c in tests:
                        allt.add(c)
                        if h == 0:
                            direct.add(c)
                    elif c in prod and c not in seen:
                        seen.add(c); nxt.add(c)
            frontier = nxt
        return direct, allt

    reach = {i: tests_reaching(i) for i in prod}
    tested_by_any = {t for i in prod for t in reach[i][1]}

    def cov_of(fs):
        tot = hit = 0
        for f in fs:
            ls = cov.get(f, {}).get('lines', {})
            tot += len(ls); hit += sum(1 for v in ls.values() if v)
        return f'{100 * hit // tot}%' if tot else '-'

    out = [f"# Codebase map: {os.path.basename(os.path.normpath(kb))}", '',
           f"Generated by codemap.py on {time.strftime('%Y-%m-%d')} from the code index ({ix['meta'].get('backend')}, "
           f"{ix['meta'].get('generated')}){' and coverage (' + str(len(cov)) + ' files)' if cov else ''}. Counted facts only; "
           'sections marked (agent) are written by the agent, every line with its source.', '']
    ntf = len({f['file'] for f in tests.values()})
    ext = collections.Counter(os.path.splitext(f)[1] for f in files)
    out += ['## At a glance', '',
            f"- {len(files)} production files ({', '.join(f'{v} {k}' for k, v in ext.most_common())}), {len(prod)} functions "
            f"({sum(1 for f in prod.values() if f.get('static'))} static, {sum(1 for f in prod.values() if f.get('virtual'))} virtual)",
            f"- {len(tests)} TEST blocks in {ntf} test files; {len(tested_by_any)} of them reach production code through the index",
            f"- {sum(1 for i in prod if not reach[i][1])} production functions reached by no TEST (directly or through 2 levels of callers)",
            f"- component = directory at depth {depth} (`--depth N` to change)", '']

    # components table
    comps = sorted(set(comp.values()))
    uses = collections.defaultdict(collections.Counter)
    for c in ix['calls']:
        a_, b_ = comp.get(c['from']), comp.get(c['to'])
        if a_ and b_ and a_ != b_:
            uses[a_][b_] += 1
    out += ['## Components', '',
            '| Component | Files | Functions | TESTs reaching it | Untested functions | Line coverage | Calls into | Called from |',
            '|---|---|---|---|---|---|---|---|']
    for cn in comps:
        ids = [i for i in prod if comp[i] == cn]
        fs = sorted({prod[i]['file'] for i in ids})
        t = {x for i in ids for x in reach[i][1]}
        un = sum(1 for i in ids if not reach[i][1])
        into = ', '.join(f'{k} ({v})' for k, v in uses[cn].most_common(4)) or '-'
        frm = ', '.join(f'{k} ({v})' for k, v in collections.Counter({k: u[cn] for k, u in uses.items() if u[cn]}).most_common(4)) or '-'
        out.append(f'| `{cn}` | {len(fs)} | {len(ids)} | {len(t)} | {un} | {cov_of(fs)} | {into} | {frm} |')

    # hotspots
    def loc(i):
        return f"{prod[i]['file']}:{prod[i]['line']}"
    hot = sorted(prod, key=lambda i: -len([c for c in callers.get(i, ()) if c in prod]))[:15]
    out += ['', '## Hotspots: most-called production functions', '',
            'A change here reaches the most code; check the callers\' tests too (resources/change-impact.md, "incl. callers").', '',
            '| Function | Where | Production callers | TESTs direct | TESTs incl. callers |', '|---|---|---|---|---|']
    for i in hot:
        n = len([c for c in callers.get(i, ()) if c in prod])
        if n:
            out.append(f"| `{prod[i]['name']}` | {loc(i)} | {n} | {len(reach[i][0])} | {len(reach[i][1])} |")

    # entry points
    entries = [i for i in prod if not [c for c in callers.get(i, ()) if c in prod] and (prod[i]['end'] or 0) > prod[i]['line']]
    out += ['', '## Entry points: functions no production code calls', '',
            'Public API, ISRs, callbacks, task bodies, main. Each is where a test (or a scenario diagram) starts.', '']
    by = collections.defaultdict(list)
    for i in entries:
        by[comp[i]].append(prod[i]['name'])
    for cn in comps:
        if by[cn]:
            names = sorted(set(by[cn]))
            out.append(f"- `{cn}` ({len(names)}): " + ', '.join(f'`{n}`' for n in names[:12]) + (' …' if len(names) > 12 else ''))

    # interfaces
    impl = collections.defaultdict(list)
    for d, b, f in ix.get('inherits', []):
        impl[b].append((d, f))
    pure = collections.Counter(f['name'].split('::')[0] for f in prod.values() if f.get('pure') and '::' in f['name'])
    out += ['', '## Interfaces and who implements them', '']
    if not impl and not pure:
        out.append('- none in the index (C code: look for structs of function pointers in the (agent) sections)')
    for b in sorted(set(impl) | set(pure)):
        ps = [f'{d} ({f})' for d, f in impl.get(b, [])]
        tp = [p for p in ps if is_test_file(p.split('(')[-1].rstrip(')'))]
        out.append(f"- `{b}`: {pure.get(b, 0)} pure virtual; implemented by {', '.join(ps[:6]) or 'nothing in the index'}"
                   + (f'; {len(tp)} in tests (fakes: every pure virtual change breaks them)' if tp else ''))

    # global state
    wr = collections.defaultdict(set)
    for i, f in prod.items():
        for g in (f.get('globals') or {}).get('written', []):
            wr[g].add(f['name'])
    shared = sorted(((g, fs) for g, fs in wr.items() if len(fs) > 1), key=lambda x: -len(x[1]))[:15]
    out += ['', '## Global state written by more than one function', '',
            'Tests must reset these in setup/teardown, or state leaks between tests (`-r2` finds it).', '']
    out += [f"- `{g}`: written by {', '.join(sorted(fs)[:6])}" for g, fs in shared] or ['- none found by the index']

    # untested
    out += ['', '## Untested: largest functions no TEST reaches', '']
    un = sorted([i for i in prod if not reach[i][1]], key=lambda i: -((prod[i]['end'] or prod[i]['line']) - prod[i]['line']))[:20]
    out += [f"- `{prod[i]['name']}` {loc(i)} ({(prod[i]['end'] or prod[i]['line']) - prod[i]['line'] + 1} lines)" for i in un
            if (prod[i]['end'] or 0) > prod[i]['line']] or ['- none']

    # agent sections
    out += ['', '## Purpose of each component (agent)', '',
            'One line per component in the table above: what it does, in the project\'s words. Source: the file header '
            'comment, README or design doc. Format: `- <component>: <purpose> (source: <file:line or doc>)`.', '',
            '## Domain words (agent)', '',
            'Abbreviations and terms a test writer meets in names and comments (e.g. "BD = buffer descriptor"). '
            'Only ones found in the code, with one place each is used.', '',
            '## Rules the code relies on (agent)', '',
            'Init order, which context calls what (ISR, task, thread), ownership and lifetime, units, locking, hardware '
            'access paths. Each line: the rule, the file:line that shows it, and what a test must do about it.', '',
            '## How the tests map to the code (agent)', '',
            'Test binaries and what each links; where tests are grouped differently from the components; components '
            'tested only through others (from the "TESTs reaching it" column); fixtures shared across files.']
    print('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1:])
