"""Greenfield: create a minimal unit-test harness (CMake) for CppUTest or GoogleTest, verified with an empty test."""
import os, re
from .util import sh, read, write, norm, say

RUNNERS = {
    'cpputest': ('#include "CppUTest/CommandLineTestRunner.h"\nint main(int ac, char** av) { return CommandLineTestRunner::RunAllTests(ac, av); }\n',
                 'find_library(CPPUTEST_LIB CppUTest REQUIRED)\nfind_library(CPPUTEST_EXT CppUTestExt REQUIRED)\n',
                 '${CPPUTEST_EXT} ${CPPUTEST_LIB}', 'main.cpp', 'smoke_test.cpp',
                 '#include "CppUTest/TestHarness.h"\nTEST_GROUP(Smoke) {};\nTEST(Smoke, HarnessBuilds) { CHECK_TRUE(true); }\n'),
    'gtest': ('', 'find_package(GTest REQUIRED)\n', 'GTest::gtest_main GTest::gmock', '', 'smoke_test.cpp',
              '#include <gtest/gtest.h>\nTEST(Smoke, HarnessBuilds) { EXPECT_TRUE(true); }\n'),
}


def include_dirs(root, prof):
    dirs = set()
    for d, dirs_, files in os.walk(root):
        rel = norm(os.path.relpath(d, root))
        dirs_[:] = [x for x in dirs_ if not x.startswith('.') and not re.match(r'build|tests?$|cmake-build', x)]
        if any(f.endswith(('.h', '.hpp', '.hh')) for f in files) and rel != '.':
            dirs.add(rel)
    return sorted(dirs)


def sources(root, prof):
    out = []
    for p in prof['code_paths']:
        for d, dirs_, files in os.walk(os.path.join(root, p)):
            out += [norm(os.path.relpath(os.path.join(d, f), root)) for f in files if f.endswith(('.c', '.cpp', '.cc', '.cxx')) and 'main' not in f]
    return sorted(out)


def create(st, fw='cpputest', test_dir='tests'):
    root, prof = st['repo'], st['profile']
    runner, find, libs, main_name, smoke_name, smoke = RUNNERS[fw]
    srcs = sources(root, prof); incs = include_dirs(root, prof)
    td = os.path.join(root, test_dir)
    cm = ['# Unit-test harness generated by the ut tool (CppUTest/GoogleTest). Add new test files to UT_SOURCES.',
          'cmake_minimum_required(VERSION 3.16)', find, 'find_package(Threads REQUIRED)',
          'set(UT_SOURCES', f'  {test_dir}/{smoke_name}'] + ([f'  {test_dir}/{main_name}'] if main_name else []) + [')',
          'set(UT_CODE_UNDER_TEST'] + [f'  ${{CMAKE_SOURCE_DIR}}/{s}' for s in srcs] + [')',
          'add_executable(unit_tests ${UT_SOURCES} ${UT_CODE_UNDER_TEST})',
          'target_include_directories(unit_tests PRIVATE ' + ' '.join(f'${{CMAKE_SOURCE_DIR}}/{i}' for i in incs) + f' ${{CMAKE_SOURCE_DIR}}/{test_dir}/mocks)',
          f'target_link_libraries(unit_tests PRIVATE {libs} Threads::Threads)',
          'target_compile_options(unit_tests PRIVATE -Wall -Wextra)',
          'add_test(NAME unit_tests COMMAND unit_tests -v)' if fw == 'cpputest' else 'include(GoogleTest)\ngtest_discover_tests(unit_tests)']
    write(os.path.join(td, 'CMakeLists.txt'), '\n'.join(cm) + '\n')
    write(os.path.join(td, smoke_name), smoke)
    if main_name:
        write(os.path.join(td, main_name), runner)
    os.makedirs(os.path.join(td, 'mocks'), exist_ok=True)
    write(os.path.join(td, 'mocks', '.keep'), '')
    # hook into the root CMakeLists
    rootcm = os.path.join(root, 'CMakeLists.txt')
    txt = read(rootcm)
    if 'add_subdirectory(' + test_dir not in txt:
        txt += f'\noption(BUILD_UNIT_TESTS "Build unit tests" OFF)\nif(BUILD_UNIT_TESTS)\n  enable_testing()\n  add_subdirectory({test_dir})\nendif()\n'
        write(rootcm, txt)
    elif 'enable_testing' not in txt:
        txt = txt.replace('add_subdirectory(' + test_dir, 'enable_testing()\n  add_subdirectory(' + test_dir, 1); write(rootcm, txt)
    b = re.search(r'-B\s*(\S+)', prof.get('build_cmd', '')) ; bdir = b.group(1) if b else 'build'
    prof['build_cmd'] = f'cmake -S . -B {bdir} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_UNIT_TESTS=ON && cmake --build {bdir} -j'
    prof['run_cmd'] = f'ctest --test-dir {bdir} --output-on-failure'
    prof['test_paths'] = [test_dir]; prof['mock_paths'] = [f'{test_dir}/mocks']; prof['framework'] = fw
    prof['mock_style'] = 'CppUMock' if fw == 'cpputest' else 'gMock'
    rc, out = sh(prof['build_cmd'] + ' && ' + prof['run_cmd'], cwd=root)
    return rc, out, [f'{test_dir}/CMakeLists.txt', f'{test_dir}/{smoke_name}'] + ([f'{test_dir}/{main_name}'] if main_name else [])
